/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import classes.CSVFileManager;
import classes.Employee;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EMAN
 */
public class FrmNewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form FrmNewEmployee
     */
    private FrmHRpage hrPageRef;

        
    public FrmNewEmployee(FrmHRpage hrPage) {
        initComponents();
        this.hrPageRef = hrPage;
    }

    //event handler method for close button
    private void FrameClose(java.awt.event.MouseEvent evt) {                            
        this.dispose();
    }       
    
    //method for clearing textfields
    private void clearTextFields() {
        txtEmployeeID.setText("");
        txtLastName.setText("");
        txtFirstName.setText("");
        jDCBirthday.setDate(null);
        txtAddress.setText("");
        txtPhoneNum.setText("");
        txtSSSNum.setText("");
        txtPhilhealthNum.setText("");
        txtTINNum.setText("");
        txtPagibigNum.setText("");
        txtStatus.setText("");
        txtPosition.setText("");
        txtDepartment.setText("");
        txtSupervisor.setText("");
        txtBasicSalary.setText("");
        txtRiceSubsidy.setText("");
        txtPhoneAllowance.setText("");
        txtClothingAllowance.setText("");
        txtGrossSemi.setText("");
        txtHourlyRate.setText("");
    }
    
    // Method to validate input
    private boolean validateInput() {
        try {
            // Validate numeric fields
            Integer.parseInt(txtEmployeeID.getText());
            Double.parseDouble(txtBasicSalary.getText());
            Double.parseDouble(txtRiceSubsidy.getText());
            Double.parseDouble(txtPhoneAllowance.getText());
            Double.parseDouble(txtClothingAllowance.getText());
            Double.parseDouble(txtGrossSemi.getText());
            Double.parseDouble(txtHourlyRate.getText());
 
        return true; // Return true if all fields pass validation
    } catch (NumberFormatException | NullPointerException ex) {
        return false; // Return false if any field fails validation
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblBirthday = new javax.swing.JLabel();
        lblPhoneNum = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblSSS = new javax.swing.JLabel();
        lblPhilhealth = new javax.swing.JLabel();
        lblTIN = new javax.swing.JLabel();
        lblPagibig = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblSupervisor = new javax.swing.JLabel();
        lblBSalary = new javax.swing.JLabel();
        lblRiceSub = new javax.swing.JLabel();
        lblPhoneAllowance = new javax.swing.JLabel();
        lblClothingAllowance = new javax.swing.JLabel();
        lblGrossSemi = new javax.swing.JLabel();
        lblHourlyRate = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        txtSSSNum = new javax.swing.JTextField();
        txtPhilhealthNum = new javax.swing.JTextField();
        txtTINNum = new javax.swing.JTextField();
        txtPagibigNum = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtSupervisor = new javax.swing.JTextField();
        txtBasicSalary = new javax.swing.JTextField();
        txtRiceSubsidy = new javax.swing.JTextField();
        txtPhoneAllowance = new javax.swing.JTextField();
        txtClothingAllowance = new javax.swing.JTextField();
        txtGrossSemi = new javax.swing.JTextField();
        txtHourlyRate = new javax.swing.JTextField();
        jDCBirthday = new com.toedter.calendar.JDateChooser();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(218, 224, 234));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 99, 140));
        jLabel1.setText("Add New Employee");

        lblEmployeeID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(78, 99, 140));
        lblEmployeeID.setText("Employee ID:");

        lblLastName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(78, 99, 140));
        lblLastName.setText("Last Name:");

        lblFirstName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(78, 99, 140));
        lblFirstName.setText("First Name:");

        lblBirthday.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBirthday.setForeground(new java.awt.Color(78, 99, 140));
        lblBirthday.setText("Birthday:");

        lblPhoneNum.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPhoneNum.setForeground(new java.awt.Color(78, 99, 140));
        lblPhoneNum.setText("Phone #:");

        lblAddress1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(78, 99, 140));
        lblAddress1.setText("Address:");

        lblSSS.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSSS.setForeground(new java.awt.Color(78, 99, 140));
        lblSSS.setText("SSS #:");

        lblPhilhealth.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPhilhealth.setForeground(new java.awt.Color(78, 99, 140));
        lblPhilhealth.setText("Philhealth #:");

        lblTIN.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTIN.setForeground(new java.awt.Color(78, 99, 140));
        lblTIN.setText("TIN #:");

        lblPagibig.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPagibig.setForeground(new java.awt.Color(78, 99, 140));
        lblPagibig.setText("Pag-ibig #:");

        lblStatus.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(78, 99, 140));
        lblStatus.setText("Status:");

        lblPosition.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(78, 99, 140));
        lblPosition.setText("Position:");

        lblDepartment.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(78, 99, 140));
        lblDepartment.setText("Department:");

        lblSupervisor.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSupervisor.setForeground(new java.awt.Color(78, 99, 140));
        lblSupervisor.setText("Supervisor:");

        lblBSalary.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblBSalary.setForeground(new java.awt.Color(78, 99, 140));
        lblBSalary.setText("Basic Salary:");

        lblRiceSub.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblRiceSub.setForeground(new java.awt.Color(78, 99, 140));
        lblRiceSub.setText("Rice Subsidy:");

        lblPhoneAllowance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPhoneAllowance.setForeground(new java.awt.Color(78, 99, 140));
        lblPhoneAllowance.setText("Phone Allowance:");

        lblClothingAllowance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblClothingAllowance.setForeground(new java.awt.Color(78, 99, 140));
        lblClothingAllowance.setText("Clothing Allowance:");

        lblGrossSemi.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblGrossSemi.setForeground(new java.awt.Color(78, 99, 140));
        lblGrossSemi.setText("Gross Semi-Monthly Rate:");

        lblHourlyRate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblHourlyRate.setForeground(new java.awt.Color(78, 99, 140));
        lblHourlyRate.setText("Hourly Rate:");

        txtEmployeeID.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtFirstName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPhoneNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtSSSNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPhilhealthNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtTINNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPagibigNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtStatus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPosition.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtDepartment.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtSupervisor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtBasicSalary.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtRiceSubsidy.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtPhoneAllowance.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtClothingAllowance.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtGrossSemi.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        txtHourlyRate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        jDCBirthday.setDateFormatString("MM/dd/yyyy");
        jDCBirthday.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnSave.setBackground(new java.awt.Color(78, 99, 140));
        btnSave.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(78, 99, 140));
        btnCancel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLastName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddress1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPhoneNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSSS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSSSNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPhilhealth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhilhealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTIN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPagibig)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPagibigNum, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmployeeID)
                                .addGap(50, 50, 50)
                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblBirthday))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jDCBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHourlyRate)
                            .addComponent(lblGrossSemi)
                            .addComponent(lblClothingAllowance)
                            .addComponent(lblPhoneAllowance)
                            .addComponent(lblRiceSub)
                            .addComponent(lblBSalary)
                            .addComponent(lblSupervisor)
                            .addComponent(lblDepartment)
                            .addComponent(lblPosition)
                            .addComponent(lblStatus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGrossSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGrossSemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeID)
                            .addComponent(lblStatus)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(lblPosition)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDepartment)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFirstName)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblBirthday)
                                .addComponent(lblSupervisor))
                            .addComponent(jDCBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBSalary)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAddress1)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhoneNum)
                            .addComponent(lblRiceSub)
                            .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSSS)
                            .addComponent(lblPhoneAllowance)
                            .addComponent(txtSSSNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhilhealth)
                            .addComponent(lblClothingAllowance)
                            .addComponent(txtPhilhealthNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTIN)
                            .addComponent(lblGrossSemi)
                            .addComponent(txtTINNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagibig)
                            .addComponent(lblHourlyRate)
                            .addComponent(txtPagibigNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Validate input before saving
    if (!validateInput()) {
        JOptionPane.showMessageDialog(this, "Invalid input. Please check the fields and try again.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Prepare empInfo array with employee information
    String[] empInfo = {
        txtEmployeeID.getText(),                // Employee ID
        txtLastName.getText(),                  // Last Name
        txtFirstName.getText(),                 // First Name
        new SimpleDateFormat("MM/dd/yyyy").format(jDCBirthday.getDate()), // Birthday
        txtAddress.getText(),                   // Address
        txtPhoneNum.getText(),                  // Phone Number
        txtSSSNum.getText(),                    // SSS Number
        txtPhilhealthNum.getText(),             // Philhealth Number
        txtTINNum.getText(),                    // TIN Number
        txtPagibigNum.getText(),                // Pagibig Number
        txtStatus.getText(),                    // Status
        txtPosition.getText(),                  // Position
        txtDepartment.getText(),                // Department
        txtSupervisor.getText(),                // Supervisor
        txtBasicSalary.getText(),               // Basic Salary
        txtRiceSubsidy.getText(),               // Rice Subsidy
        txtPhoneAllowance.getText(),            // Phone Allowance
        txtClothingAllowance.getText(),         // Clothing Allowance
        txtGrossSemi.getText(),                 // Gross Semi
        txtHourlyRate.getText()                 // Hourly Rate
    };

    // Update table in FrmHRpage with the new employee record
    hrPageRef.updateTable(empInfo);
    
    // Update CSV file with data from the table in FrmHRpage
    String csvFilePath = "src\\main\\java\\files\\Employee.csv";
    JTable table = hrPageRef.getTblEmpInfo(); // Assuming getTable() returns the JTable instance in FrmHRpage
    CSVFileManager.updateCSVFile(csvFilePath, table);
    
    // Show success message
    JOptionPane.showMessageDialog(this, "Employee record saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
    
    // Clear text fields after saving
    clearTextFields();


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jDCBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblBSalary;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblClothingAllowance;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGrossSemi;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPagibig;
    private javax.swing.JLabel lblPhilhealth;
    private javax.swing.JLabel lblPhoneAllowance;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblRiceSub;
    private javax.swing.JLabel lblSSS;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JLabel lblTIN;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBasicSalary;
    private javax.swing.JTextField txtClothingAllowance;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGrossSemi;
    private javax.swing.JTextField txtHourlyRate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPagibigNum;
    private javax.swing.JTextField txtPhilhealthNum;
    private javax.swing.JTextField txtPhoneAllowance;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtRiceSubsidy;
    private javax.swing.JTextField txtSSSNum;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtSupervisor;
    private javax.swing.JTextField txtTINNum;
    // End of variables declaration//GEN-END:variables
}
