/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Raya
 */
public class FrmSalary extends javax.swing.JFrame {

    /**
     * Creates new form FrmSalary
     */
    public FrmSalary() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLogoMotorPH = new javax.swing.JLabel();
        lblWelcomeMsg = new javax.swing.JLabel();
        logOut_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblSalaryInfo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblDeductions = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblAllowance = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblHourlyRate = new javax.swing.JLabel();
        txtHourlyRate = new javax.swing.JTextField();
        lblMonthlyRate = new javax.swing.JLabel();
        txtMonthlyRate = new javax.swing.JTextField();
        lblGrossSalary = new javax.swing.JLabel();
        txtGrossSalary = new javax.swing.JTextField();
        lblNetSalary = new javax.swing.JLabel();
        txtNetSalary = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblPeriodStartDate = new javax.swing.JLabel();
        txtPeriodStartDate = new javax.swing.JTextField();
        lblPeriodEndDate = new javax.swing.JLabel();
        txtPeriodEndDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblSSSdeductions = new javax.swing.JLabel();
        txtSSSdeductions = new javax.swing.JTextField();
        lblPagibigDeductions = new javax.swing.JLabel();
        txtPagibigDeductions = new javax.swing.JTextField();
        lblPhilhealthDeductions = new javax.swing.JLabel();
        txtPhilhealthDeductions = new javax.swing.JTextField();
        lblWithholdingTax = new javax.swing.JLabel();
        txtWithholdingTax = new javax.swing.JTextField();
        lblTotalDeductions = new javax.swing.JLabel();
        txtTotalDeductions = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        lblRiceSubsidy = new javax.swing.JLabel();
        txtRiceSubsidy = new javax.swing.JTextField();
        lblPhoneAllowance = new javax.swing.JLabel();
        txtPhoneAllowance = new javax.swing.JTextField();
        lblClothingAllowance = new javax.swing.JLabel();
        txtClothingAllowance = new javax.swing.JTextField();
        lblTotalAllowance = new javax.swing.JLabel();
        txtTotalAllowance = new javax.swing.JTextField();
        profile_button = new javax.swing.JButton();
        attendance_button = new javax.swing.JButton();
        request_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 226, 227));
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(1020, 680));
        setPreferredSize(new java.awt.Dimension(1080, 680));

        jPanel1.setBackground(new java.awt.Color(218, 226, 227));

        jPanel2.setBackground(new java.awt.Color(53, 66, 68));

        lblLogoMotorPH.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        lblLogoMotorPH.setForeground(new java.awt.Color(208, 228, 230));
        lblLogoMotorPH.setText("MotorPH");

        lblWelcomeMsg.setFont(new java.awt.Font("Verdana", 0, 25)); // NOI18N
        lblWelcomeMsg.setForeground(new java.awt.Color(208, 228, 230));
        lblWelcomeMsg.setText("Welcome!");

        logOut_button.setBackground(new java.awt.Color(53, 66, 68));
        logOut_button.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        logOut_button.setForeground(new java.awt.Color(255, 255, 255));
        logOut_button.setText("Log out");
        logOut_button.setAutoscrolls(true);
        logOut_button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logOut_button.setBorderPainted(false);
        logOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 214, 214));
        jLabel3.setText("|");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DREAM PC\\Documents\\NetBeansProjects\\PayrollSystemMaven\\src\\main\\java\\icons\\Untitled design (2).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLogoMotorPH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcomeMsg)
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(logOut_button, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(logOut_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblWelcomeMsg))
                            .addComponent(lblLogoMotorPH))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(108, 133, 136));

        lblSalaryInfo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblSalaryInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblSalaryInfo.setText("Salary Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalaryInfo)
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSalaryInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(140, 172, 177));

        lblDeductions.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDeductions.setForeground(new java.awt.Color(255, 255, 255));
        lblDeductions.setText("Deductions");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDeductions)
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeductions, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(108, 133, 136));

        lblAllowance.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAllowance.setForeground(new java.awt.Color(255, 255, 255));
        lblAllowance.setText("Allowance");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(lblAllowance)
                .addGap(109, 109, 109))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAllowance, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(140, 172, 177));

        lblHourlyRate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblHourlyRate.setForeground(new java.awt.Color(255, 255, 255));
        lblHourlyRate.setText("Hourly Rate:");

        txtHourlyRate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblMonthlyRate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblMonthlyRate.setForeground(new java.awt.Color(255, 255, 255));
        lblMonthlyRate.setText("Monthly Rate:");

        txtMonthlyRate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblGrossSalary.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblGrossSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblGrossSalary.setText("Gross Salary:");

        txtGrossSalary.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblNetSalary.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        lblNetSalary.setForeground(new java.awt.Color(255, 255, 255));
        lblNetSalary.setText("Net Salary:");

        txtNetSalary.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblEmployeeID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeID.setText("Employee ID:");

        txtEmployeeID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIDActionPerformed(evt);
            }
        });

        lblPeriodStartDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPeriodStartDate.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodStartDate.setText("Period Start Date:");

        txtPeriodStartDate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPeriodStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeriodStartDateActionPerformed(evt);
            }
        });

        lblPeriodEndDate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPeriodEndDate.setForeground(new java.awt.Color(255, 255, 255));
        lblPeriodEndDate.setText("Period End Date:");

        txtPeriodEndDate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblEmployeeID))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblPeriodStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPeriodEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(txtPeriodStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(txtPeriodEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblNetSalary)
                                .addComponent(lblGrossSalary)
                                .addComponent(lblMonthlyRate)
                                .addComponent(lblHourlyRate)
                                .addComponent(txtHourlyRate, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addComponent(txtMonthlyRate)
                                .addComponent(txtGrossSalary)
                                .addComponent(txtNetSalary)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblEmployeeID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodStartDate)
                    .addComponent(lblPeriodEndDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPeriodStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeriodEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHourlyRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHourlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonthlyRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMonthlyRate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrossSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrossSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNetSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNetSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel7.setBackground(new java.awt.Color(173, 202, 206));

        lblSSSdeductions.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSSSdeductions.setForeground(new java.awt.Color(255, 255, 255));
        lblSSSdeductions.setText("SSS Deductions:");

        txtSSSdeductions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSSSdeductions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSSdeductionsActionPerformed(evt);
            }
        });

        lblPagibigDeductions.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPagibigDeductions.setForeground(new java.awt.Color(255, 255, 255));
        lblPagibigDeductions.setText("Pag-IBIG Deductions:");

        txtPagibigDeductions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblPhilhealthDeductions.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPhilhealthDeductions.setForeground(new java.awt.Color(255, 255, 255));
        lblPhilhealthDeductions.setText("PhilHealth Deductions:");

        txtPhilhealthDeductions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblWithholdingTax.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblWithholdingTax.setForeground(new java.awt.Color(255, 255, 255));
        lblWithholdingTax.setText("Withholding Tax:");

        txtWithholdingTax.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblTotalDeductions.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTotalDeductions.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalDeductions.setText("Total Deductions:");

        txtTotalDeductions.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalDeductions)
                    .addComponent(lblWithholdingTax)
                    .addComponent(lblPhilhealthDeductions)
                    .addComponent(lblPagibigDeductions)
                    .addComponent(lblSSSdeductions)
                    .addComponent(txtSSSdeductions)
                    .addComponent(txtPagibigDeductions)
                    .addComponent(txtPhilhealthDeductions)
                    .addComponent(txtWithholdingTax)
                    .addComponent(txtTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblSSSdeductions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSSSdeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPagibigDeductions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPagibigDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhilhealthDeductions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhilhealthDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWithholdingTax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWithholdingTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalDeductions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDeductions, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(140, 172, 177));

        lblRiceSubsidy.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblRiceSubsidy.setForeground(new java.awt.Color(255, 255, 255));
        lblRiceSubsidy.setText("Rice Subsidy:");

        txtRiceSubsidy.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRiceSubsidy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRiceSubsidyActionPerformed(evt);
            }
        });

        lblPhoneAllowance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPhoneAllowance.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneAllowance.setText("Phone Allowance:");

        txtPhoneAllowance.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPhoneAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneAllowanceActionPerformed(evt);
            }
        });

        lblClothingAllowance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblClothingAllowance.setForeground(new java.awt.Color(255, 255, 255));
        lblClothingAllowance.setText("Clothing Allowance:");

        txtClothingAllowance.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtClothingAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClothingAllowanceActionPerformed(evt);
            }
        });

        lblTotalAllowance.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTotalAllowance.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalAllowance.setText("Total Allowance:");

        txtTotalAllowance.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtTotalAllowance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAllowanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalAllowance)
                    .addComponent(lblClothingAllowance)
                    .addComponent(lblPhoneAllowance)
                    .addComponent(txtRiceSubsidy, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(lblRiceSubsidy)
                    .addComponent(txtPhoneAllowance)
                    .addComponent(txtClothingAllowance)
                    .addComponent(txtTotalAllowance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRiceSubsidy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRiceSubsidy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhoneAllowance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClothingAllowance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClothingAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalAllowance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profile_button.setBackground(new java.awt.Color(53, 66, 68));
        profile_button.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        profile_button.setForeground(new java.awt.Color(255, 255, 255));
        profile_button.setText("Profile");
        profile_button.setMaximumSize(new java.awt.Dimension(131, 30));
        profile_button.setMinimumSize(new java.awt.Dimension(131, 30));
        profile_button.setPreferredSize(new java.awt.Dimension(131, 30));
        profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_buttonActionPerformed(evt);
            }
        });

        attendance_button.setBackground(new java.awt.Color(53, 66, 68));
        attendance_button.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        attendance_button.setForeground(new java.awt.Color(255, 255, 255));
        attendance_button.setText("Attendance");
        attendance_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendance_buttonActionPerformed(evt);
            }
        });

        request_button.setBackground(new java.awt.Color(53, 66, 68));
        request_button.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        request_button.setForeground(new java.awt.Color(255, 255, 255));
        request_button.setText("Request");
        request_button.setMaximumSize(new java.awt.Dimension(131, 30));
        request_button.setMinimumSize(new java.awt.Dimension(131, 30));
        request_button.setPreferredSize(new java.awt.Dimension(131, 30));
        request_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                request_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(attendance_button, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(request_button, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendance_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(request_button, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_buttonActionPerformed
        // TODO add your handling code here:
        FrmLogin logOut = new FrmLogin();
            logOut.show();
            
            dispose();
    }//GEN-LAST:event_logOut_buttonActionPerformed

    private void request_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_request_buttonActionPerformed
        // TODO add your handling code here:
        FrmRequest request = new FrmRequest();
            request.show();
            
            dispose();
    }//GEN-LAST:event_request_buttonActionPerformed

    private void txtSSSdeductionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSSdeductionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSSdeductionsActionPerformed

    private void txtRiceSubsidyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRiceSubsidyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRiceSubsidyActionPerformed

    private void txtPhoneAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneAllowanceActionPerformed

    private void txtClothingAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClothingAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClothingAllowanceActionPerformed

    private void txtTotalAllowanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAllowanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAllowanceActionPerformed

    private void txtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIDActionPerformed

    private void txtPeriodStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeriodStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeriodStartDateActionPerformed

    private void profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_buttonActionPerformed
        // TODO add your handling code here:
        FrmEmployee_Information empInfo = new FrmEmployee_Information();
        empInfo.show();

        dispose();
    }//GEN-LAST:event_profile_buttonActionPerformed

    private void attendance_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendance_buttonActionPerformed
        // TODO add your handling code here:
        FrmAttendance attendance = new FrmAttendance();
        attendance.show();

        dispose();
    }//GEN-LAST:event_attendance_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendance_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblAllowance;
    private javax.swing.JLabel lblClothingAllowance;
    private javax.swing.JLabel lblDeductions;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblGrossSalary;
    private javax.swing.JLabel lblHourlyRate;
    private javax.swing.JLabel lblLogoMotorPH;
    private javax.swing.JLabel lblMonthlyRate;
    private javax.swing.JLabel lblNetSalary;
    private javax.swing.JLabel lblPagibigDeductions;
    private javax.swing.JLabel lblPeriodEndDate;
    private javax.swing.JLabel lblPeriodStartDate;
    private javax.swing.JLabel lblPhilhealthDeductions;
    private javax.swing.JLabel lblPhoneAllowance;
    private javax.swing.JLabel lblRiceSubsidy;
    private javax.swing.JLabel lblSSSdeductions;
    private javax.swing.JLabel lblSalaryInfo;
    private javax.swing.JLabel lblTotalAllowance;
    private javax.swing.JLabel lblTotalDeductions;
    private javax.swing.JLabel lblWelcomeMsg;
    private javax.swing.JLabel lblWithholdingTax;
    private javax.swing.JButton logOut_button;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton request_button;
    private javax.swing.JTextField txtClothingAllowance;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtGrossSalary;
    private javax.swing.JTextField txtHourlyRate;
    private javax.swing.JTextField txtMonthlyRate;
    private javax.swing.JTextField txtNetSalary;
    private javax.swing.JTextField txtPagibigDeductions;
    private javax.swing.JTextField txtPeriodEndDate;
    private javax.swing.JTextField txtPeriodStartDate;
    private javax.swing.JTextField txtPhilhealthDeductions;
    private javax.swing.JTextField txtPhoneAllowance;
    private javax.swing.JTextField txtRiceSubsidy;
    private javax.swing.JTextField txtSSSdeductions;
    private javax.swing.JTextField txtTotalAllowance;
    private javax.swing.JTextField txtTotalDeductions;
    private javax.swing.JTextField txtWithholdingTax;
    // End of variables declaration//GEN-END:variables
}
